### ISSUE TITLE
OutPut Size Cant be 1242*375

### ISSUE THREAD

**Issue by wangjiyuan9** [svip-lab/PlaneDepth#8]
Dear Author:
I am currently using the PlaneDepth model for image depth prediction. However, I am encountering issues while trying to predict the depth of an image to the resolution of 1242x375(It is the orgin resloution of kitti dataset. And I mean in the eva.sh, I use --width 1242 --height 375)
`Traceback (most recent call last):
  File xx/PlaneDepth/out_depth.py", line 181, in <module>
    evaluate(options.parse())
  File "xx/PlaneDepth/out_depth.py", line 136, in evaluate
    output = depth_decoder(encoder(input_color), grids)
  File "xx/PlaneDepth/networks/depth_decoder.py", line 136, in forward
    x = torch.cat(x, 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 48 but got size 47 for tensor number 1 in the list.`

**Comment by Dwawayu** [comment]
Hi! Our U-Net needs height and width of input to be a multiple of 32.
